"""add gateway

Revision ID: 3f8a02b537a0
Revises: 0a70d9ff1920
Create Date: 2025-11-29 11:12:07.189000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f8a02b537a0'
down_revision: Union[str, Sequence[str], None] = '0a70d9ff1920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gateways',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mac', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('geolocation', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_gateways_mac'), 'gateways', ['mac'], unique=True)
    op.add_column('tags', sa.Column('battery_level', sa.Integer(), nullable=True))
    op.add_column('tags', sa.Column('gateway_mac', sa.String(), nullable=True))
    op.create_index('idx_mac_timestamp', 'tags', ['mac', 'timestamp'], unique=False)
    op.create_index(op.f('ix_tags_timestamp'), 'tags', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'tags', 'gateways', ['gateway_mac'], ['mac'], ondelete='SET NULL')
    op.drop_column('tags', 'gateway')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('gateway', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_index(op.f('ix_tags_timestamp'), table_name='tags')
    op.drop_index('idx_mac_timestamp', table_name='tags')
    op.drop_column('tags', 'gateway_mac')
    op.drop_column('tags', 'battery_level')
    op.drop_index(op.f('ix_gateways_mac'), table_name='gateways')
    op.drop_table('gateways')
    # ### end Alembic commands ###
